# Generated by Django 4.2.16 on 2024-11-21 13:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content_type', models.CharField(choices=[('EBOOK', 'eBook'), ('AUDIOBOOK', 'Audiobook')], max_length=10)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI'), ('MP3', 'MP3'), ('M4B', 'M4B')], max_length=10)),
                ('file', models.FileField(upload_to='digital_content/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub', 'mobi', 'mp3', 'm4b'])])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='digital_content/covers/')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=50)),
                ('size_mb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('RETURNED', 'Returned')], default='ACTIVE', max_length=10)),
                ('download_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='digital_library.digitalcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalContentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='digital_library.digitalcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('content', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DigitalContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=0)),
                ('current_position', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('bookmarks', models.JSONField(default=list)),
                ('notes', models.JSONField(default=dict)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_library.digitalcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
    ]
