# Generated by Django 4.2.16 on 2024-11-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('FINE', 'Library Fine'), ('MEMBERSHIP', 'Membership Fee'), ('DONATION', 'Donation'), ('LATE_FEE', 'Late Return Fee'), ('PRINTING', 'Printing Service'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15)),
                ('description', models.TextField()),
                ('received_from', models.CharField(max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('SALARY', 'Staff Salary'), ('MAINTENANCE', 'Maintenance'), ('BOOKS', 'Book Purchase'), ('UTILITIES', 'Utilities'), ('SUPPLIES', 'Office Supplies'), ('EQUIPMENT', 'Equipment'), ('SOFTWARE', 'Software/Digital Resources'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check')], max_length=15)),
                ('description', models.TextField()),
                ('paid_to', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
