# Generated by Django 4.2.16 on 2024-11-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberactivity',
            options={'ordering': ['-activity_date'], 'verbose_name_plural': 'Member Activities'},
        ),
        migrations.AlterModelOptions(
            name='renewalreminder',
            options={'ordering': ['reminder_date']},
        ),
        migrations.AddField(
            model_name='memberactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATE', 'Membership Created'), ('UPDATE', 'Membership Updated'), ('RENEW', 'Membership Renewed'), ('EXPIRE', 'Membership Expired'), ('CANCEL', 'Membership Cancelled'), ('PAYMENT', 'Payment Recorded')], default='CREATE', max_length=20),
        ),
        migrations.AddField(
            model_name='renewalreminder',
            name='response',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RENEWED', 'Renewed'), ('DECLINED', 'Declined'), ('NO_RESPONSE', 'No Response')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='renewalreminder',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
