# Generated by Django 4.2.16 on 2024-11-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='address',
            field=models.TextField(),
        ),
    ]
