# Generated by Django 5.1.3 on 2024-11-19 04:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog', '0002_alter_book_authors_alter_book_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('floor', models.PositiveIntegerField(help_text='Floor number where the shelf is located', validators=[django.core.validators.MinValueValidator(1)])),
                ('section', models.CharField(help_text="Section identifier (e.g., 'A', 'B', 'Science', 'History')", max_length=50)),
                ('total_rows', models.PositiveIntegerField(help_text='Number of rows in this shelf', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_columns', models.PositiveIntegerField(help_text='Number of columns in this shelf', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'unique_together': {('floor', 'section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(help_text='Row number in the shelf', validators=[django.core.validators.MinValueValidator(1)])),
                ('column', models.PositiveIntegerField(help_text='Column number in the shelf', validators=[django.core.validators.MinValueValidator(1)])),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='book_catalog.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_locations', to='book_catalog.shelf')),
            ],
            options={
                'unique_together': {('shelf', 'row', 'column')},
            },
        ),
    ]
